# Generated by Django 4.2.3 on 2023-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='f_fin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='f_inicio',
            field=models.IntegerField(),
        ),
    ]
