# Generated by Django 4.2.3 on 2023-07-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_generos_series_peliculas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directores',
            new_name='Directore',
        ),
        migrations.RenameModel(
            old_name='Generos',
            new_name='Genero',
        ),
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Pelicula',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
