# Generated by Django 4.2.3 on 2023-07-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_duracion_alter_serie_f_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='sinopsis',
            field=models.TextField(),
        ),
    ]
