# Generated by Django 4.2.3 on 2023-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_alter_serie_f_fin_alter_serie_f_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='f_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
