# Generated by Django 4.2.3 on 2023-08-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['nickname']},
        ),
    ]
