# Generated by Django 4.2.3 on 2023-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='descripcion',
            field=models.TextField(verbose_name='Presentate'),
        ),
    ]
